fixed terra tests and new tests
threefoldtech/terraform-provider-grid pull request #396
Opened 2022-12-06 14:13 UTC by khaledyoussef24

provided new tests and fixed the old tests to the latest updates

2022-12-07 11:19 UTC, mohamedamer453 requested changes

2022-12-07 11:19 UTC, mohamedamer453 commented on tests/mattermost/main.tf
> +    node = 2
Change this node id with the id of a gateway node on testnet. same thing for the node id in line `59`

2022-12-07 11:19 UTC, mohamedamer453 commented on tests/peertube/main.tf
> +    node = 3
Change this node id with the id of a gateway node on testnet. same thing for the node id in line `61`

2022-12-07 11:19 UTC, mohamedamer453 commented on tests/taiga/main.tf
> +  node            = 2
Change both node ids with the id of a gateway node on testnet.

2022-12-07 11:22 UTC, mohamedamer453 commented
Also some tests failed when i tried to run them.

- Peertube

   Test Failed with the following error:
   ```
   │ Error: couldn't generate deployments data: failed to assign node ips: invalid ip : invalid CIDR address: 
   ```

- taiga
   Test Failed with the following error:
   ```
   	taiga_test.go:64: 
                Error Trace:    taiga_test.go:64
                Error:          "superuser-init: Running\nufw: Running\nsshd: Running\ncontainerd: Blocked\nsshd-init: Success\ndockerd: Blocked\ntaiga: Blocked\nufw-init: Success\n" does not contain "containerd: Running"
   ```

2022-12-08 07:21 UTC, khaledyoussef24 commented on tests/mattermost/mattermost_test.go
> +	assert.Contains(t, res1, "mattermost: Running")
even when the service is working and built up it is running not success 

![Screenshot from 2022-12-08 09-11-03](https://user-images.githubusercontent.com/110984055/206382135-62f64f1d-7a7b-4cfb-9633-9f9b9926b241.png)

2022-12-08 11:06 UTC, khaledyoussef24 commented on tests/taiga/taiga_test.go
> +	assert.Contains(t, res1, "containerd: Running")
i will change it to taiga running

![Screenshot from 2022-12-08 13-03-18](https://user-images.githubusercontent.com/110984055/206431412-c1d7f1f0-2938-4f71-8610-0baeb647335e.png)

2022-12-08 14:14 UTC, mohamedamer453 commented
All of the requested changes were resolved except for one. please check it again.

I ran the tests but a couple failed with the following errors.

 - Presearch
   
   ```
    Error Trace:    presearch_test.go:67
                   Error:          "---\nsshkey: Success\nprerestorer: Success\nsshd: Running\npreupdater: \"Error(Exited(Pid(287), 125))\"\nprenode: \"Error(Exited(Pid(288), 125))\"\ndockerd: Running\n" does not contain "prenode: Success"
   ```

- kubernetes_with_k8s_module
```
    apply.go:15: 
                Error Trace:    apply.go:15
                                                        kubernetes_test.go:53
                Error:          Received unexpected error:
                                FatalError{Underlying: error while running command: exit status 1; There are some problems with the configuration, described below.
                            
                                The Terraform configuration must be valid before initialization so that
                                Terraform can determine which modules and providers need to be installed.
                                ╷
                                │ Error: Invalid validation error message
                                │ 
                                │   on .terraform/modules/kubernetes/modules/k8s-module/variables.tf line 33, in variable "master":
                                │   33:     error_message = "Memory must be at least 1GB"
                                │ 
                                │ The validation error message must be at least one full sentence starting
                                │ with an uppercase letter and ending with a period or question mark.
                                │ 
                                │ Your given message will be included as part of a larger Terraform error
                                │ message, written as English prose. For broadly-shared modules we suggest
                                │ using a similar writing style so that the overall result will be
                                │ consistent.
                                ╵
                            
                                ╷
                                │ Error: Invalid validation error message
                                │ 
                                │   on .terraform/modules/kubernetes/modules/k8s-module/variables.tf line 53, in variable "workers":
                                │   53:     error_message = "Memory must be at least 1GB"
                                │ 
                                │ The validation error message must be at least one full sentence starting
                                │ with an uppercase letter and ending with a period or question mark.
                                │ 
                                │ Your given message will be included as part of a larger Terraform error
                                │ message, written as English prose. For broadly-shared modules we suggest
                                │ using a similar writing style so that the overall result will be
                                │ consistent.
                                ╵
                            
                                ╷
                                │ Error: Invalid validation error message
                                │ 
                                │   on .terraform/modules/kubernetes/modules/k8s-module/validator/main.tf line 5, in variable "names":
                                │    5:     error_message = "Master and workers names must be distinct"
                                │ 
                                │ The validation error message must be at least one full sentence starting
                                │ with an uppercase letter and ending with a period or question mark.
                                │ 
                                │ Your given message will be included as part of a larger Terraform error
                                │ message, written as English prose. For broadly-shared modules we suggest
                                │ using a similar writing style so that the overall result will be
                                │ consistent.
                                ╵

```

- And the one i mentioned before wasn't fixed

> * singlenode_key_ed25519
>   This test also failed since it was not updated with the new format, you might need to remove [this line ](https://github.com/threefoldtech/terraform-provider-grid/blob/development/tests/singlenode_key_ed25519/main.tf#L29) from it like the rest of the tests that you updated.

2022-12-11 12:30 UTC, mohamedamer453 commented
All issues were fixed/resolved and the tests that were failing are passing now, the only issue left is the ` kubernetes_with_k8s_module`  with the same errors reported from last time, and after going over this error messages again i realized that they're not originating from the tests but from the module itself.




> * kubernetes_with_k8s_module
> 
> ```
>     apply.go:15: 
>                 Error Trace:    apply.go:15
>                                                         kubernetes_test.go:53
>                 Error:          Received unexpected error:
>                                 FatalError{Underlying: error while running command: exit status 1; There are some problems with the configuration, described below.
>                             
>                                 The Terraform configuration must be valid before initialization so that
>                                 Terraform can determine which modules and providers need to be installed.
>                                 ╷
>                                 │ Error: Invalid validation error message
>                                 │ 
>                                 │   on .terraform/modules/kubernetes/modules/k8s-module/variables.tf line 33, in variable "master":
>                                 │   33:     error_message = "Memory must be at least 1GB"
>                                 │ 
>                                 │ The validation error message must be at least one full sentence starting
>                                 │ with an uppercase letter and ending with a period or question mark.
>                                 │ 
>                                 │ Your given message will be included as part of a larger Terraform error
>                                 │ message, written as English prose. For broadly-shared modules we suggest
>                                 │ using a similar writing style so that the overall result will be
>                                 │ consistent.
>                                 ╵
>                             
>                                 ╷
>                                 │ Error: Invalid validation error message
>                                 │ 
>                                 │   on .terraform/modules/kubernetes/modules/k8s-module/variables.tf line 53, in variable "workers":
>                                 │   53:     error_message = "Memory must be at least 1GB"
>                                 │ 
>                                 │ The validation error message must be at least one full sentence starting
>                                 │ with an uppercase letter and ending with a period or question mark.
>                                 │ 
>                                 │ Your given message will be included as part of a larger Terraform error
>                                 │ message, written as English prose. For broadly-shared modules we suggest
>                                 │ using a similar writing style so that the overall result will be
>                                 │ consistent.
>                                 ╵
>                             
>                                 ╷
>                                 │ Error: Invalid validation error message
>                                 │ 
>                                 │   on .terraform/modules/kubernetes/modules/k8s-module/validator/main.tf line 5, in variable "names":
>                                 │    5:     error_message = "Master and workers names must be distinct"
>                                 │ 
>                                 │ The validation error message must be at least one full sentence starting
>                                 │ with an uppercase letter and ending with a period or question mark.
>                                 │ 
>                                 │ Your given message will be included as part of a larger Terraform error
>                                 │ message, written as English prose. For broadly-shared modules we suggest
>                                 │ using a similar writing style so that the overall result will be
>                                 │ consistent.
>                                 ╵
> ```

2022-12-11 12:32 UTC, mohamedamer453 approved these changes

2022-12-11 14:02 UTC, merged