refactor using go client
threefoldtech/terraform-provider-grid pull request #592
Opened 2023-04-03 09:30 UTC by rawdaGastan

## Issues

- https://github.com/threefoldtech/terraform-provider-grid/issues/554

2023-04-03 15:37 UTC, ashraffouda commented on internal/provider/deployment.go
> +	// TODO: ip_range
remove unneeded code plz

2023-04-05 21:09 UTC, ashraffouda requested changes

2023-04-05 21:09 UTC, ashraffouda commented on internal/provider/gateway_name.go
> +	var contractID uint64
same as above let's remove unnecessary if statements

2023-04-05 21:09 UTC, ashraffouda commented on internal/provider/gateway_name_test.go
> -// Package provider is the terraform provider
why did we remove tests?

2023-04-05 21:09 UTC, ashraffouda commented on internal/provider/k8s.go
> +	if masterIP == nil {
is master doesn't have valid ip this is an issue, no?

2023-04-05 21:09 UTC, ashraffouda commented on internal/provider/provider.go
> +		// TODO:
let's remove those comments

2023-04-06 20:35 UTC, MarioBassem submitted a review, later dismissed
access nodes are not deleted while destroying networks.
i took a look at the code and found that only the contracts on the user-specified nodes are deleted when deleting a network resource, which i think is not wanted behavior???

2023-04-09 11:36 UTC, AbdelrahmanElawady reviewed
looks good, some minor comments

2023-04-09 14:44 UTC, xmonader reviewed
I'm very happy with the PR, It's huge step forward!

2023-04-09 15:04 UTC, rawdaGastan commented on internal/provider/k8s.go
> +		deploymentID := uint64(id.(int))
terraform doesn't accept uint64 interface

2023-04-10 09:31 UTC, rawdaGastan commented on internal/provider/k8s.go
> +		workerNodeDeploymentHostIDs := network.GetDeploymentHostIDs(worker.Node, k8s.NodeDeploymentID[worker.Node])
no as we set them per node

2023-04-10 09:31 UTC, rawdaGastan commented on internal/provider/k8s.go
> +		NodesIPRange:     nodesIPRange,
its calculated through deployment

2023-04-11 10:05 UTC, xmonader approved these changes

2023-04-11 10:06 UTC, merged